### ISSUE TITLE
Help regarding the documentation

### ISSUE THREAD

**Issue by stachyris** [kfuku52/mcmctree_tree_prep#1]
Hi there.! I am trying to use this programme to prepare the input for MCMCTree, but I am failing miserably in understanding the parameters. Could you please help me understand what exactly --left_species  and  --right_species commands are.? Thank you.

**Comment by kfuku52** [comment]
Thank you for interested in this tool! The node to which the constraint is added is determined by searching the last common ancestor between --left_species and --right_species. So, it should look like this:
![image](https://user-images.githubusercontent.com/19270515/88267174-c181e200-ccd0-11ea-8430-acbd5699aa57.png)

**Comment by stachyris** [comment]
> 
> 
> Thank you for interested in this tool! The node to which the constraint is added is determined by searching the last common ancestor between --left_species and --right_species. So, it should look like this:
> ![image](https://user-images.githubusercontent.com/19270515/88267174-c181e200-ccd0-11ea-8430-acbd5699aa57.png)

Appreciate the quick response. So I don't need to specify all the leaves! That was my initial doubt. Thanks again for the help.
